import { Dataset } from "@/lib/domain/schema";
import { evidence } from "./evidence";
import { jurisdictions } from "./jurisdictions";
import { mechanisms } from "./mechanisms";
import { metrics } from "./metrics";
import { outcomes } from "./outcomes";
import { policies } from "./policies";
import { similarities } from "./similarities";
import { computedSimilarities } from "./computed";
import { technologies } from "./technologies";
import { timeSeries } from "./time-series";

// curated seeds win; computed pairs (generated by `pnpm embed`) fill the rest
const curatedIds = new Set(similarities.map((s) => s.id));
const mergedSimilarities = [
  ...similarities,
  ...computedSimilarities.filter((s) => !curatedIds.has(s.id)),
];

export const curatedDataset: Dataset = Dataset.parse({
  jurisdictions,
  technologies,
  mechanisms,
  metrics,
  policies,
  evidence,
  outcomes,
  time_series: timeSeries,
  similarities: mergedSimilarities,
});
