/**
 * Generates local policy and evidence embeddings plus semantic pair scores.
 * Usage: pnpm embed
 */
import { writeFileSync } from "node:fs";
import path from "node:path";

import { pipeline } from "@huggingface/transformers";
import { seedDataset } from "../src/data/seed";
const MODEL = "Xenova/all-MiniLM-L6-v2";
const DIMS = 384;
const BATCH_SIZE = 16;
const IMPORTED_NEIGHBOURS = 8;

type FeatureExtractionOutput = { tolist(): number[][] };
type FeatureExtractionPipeline = (
  texts: string[],
  options: { pooling: "mean"; normalize: true },
) => Promise<FeatureExtractionOutput>;

async function embedAll(
  items: { id: string; text: string }[],
  extractor: FeatureExtractionPipeline,
): Promise<Record<string, number[]>> {
  const out: Record<string, number[]> = {};
  for (let i = 0; i < items.length; i += BATCH_SIZE) {
    const batch = items.slice(i, i + BATCH_SIZE);
    const output = await extractor(batch.map((item) => item.text), {
      pooling: "mean",
      normalize: true,
    });
    const vectors = output.tolist() as number[][];
    batch.forEach((item, j) => {
      const vector = vectors[j];
      if (!vector || vector.length !== DIMS)
        throw new Error(`Expected a ${DIMS}-dimensional embedding for ${item.id}`);
      out[item.id] = vector.map((value) => Number(value.toFixed(5)));
    });
    console.log(`embedded ${Math.min(i + BATCH_SIZE, items.length)}/${items.length}`);
  }
  return out;
}

function cosine(a: number[], b: number[]): number {
  let dot = 0;
  let normA = 0;
  let normB = 0;
  for (let i = 0; i < a.length; i++) {
    dot += a[i] * b[i];
    normA += a[i] * a[i];
    normB += b[i] * b[i];
  }
  return normA && normB ? dot / Math.sqrt(normA * normB) : 0;
}

async function main() {
  const createPipeline = pipeline as unknown as (
    task: "feature-extraction",
    model: string,
  ) => Promise<FeatureExtractionPipeline>;
  const extractor = await createPipeline("feature-extraction", MODEL);
  const policies = await embedAll(
    seedDataset.policies.map((p) => ({
      id: p.id,
      text: `${p.name}\n${p.description}\n${p.incentive}`,
    })),
    extractor,
  );
  const evidence = await embedAll(
    seedDataset.evidence.map((e) => ({
      id: e.id,
      text: `${e.title}\n${e.findings.join(" ")}`,
    })),
    extractor,
  );

  const embeddingsFile = path.join(process.cwd(), "src/data/seed/embeddings.json");
  writeFileSync(
    embeddingsFile,
    JSON.stringify({ model: MODEL, dims: DIMS, policies, evidence }),
  );
  console.log(
    `wrote ${embeddingsFile} (${Object.keys(policies).length} policies, ${Object.keys(evidence).length} evidence)`,
  );

  const pairScore = (a: string, b: string) =>
    Number(Math.max(0, Math.min(1, (cosine(policies[a], policies[b]) + 1) / 2)).toFixed(3));
  const pairKey = (a: string, b: string) => [a, b].sort().join("|");

  // every curated pair; imported (CPDB) policies keep only their nearest
  // neighbours so the client-side score table stays small
  const scores: Record<string, number> = {};
  const curated = seedDataset.policies.filter((p) => p.data_status !== "IMPORTED");
  const imported = seedDataset.policies.filter((p) => p.data_status === "IMPORTED");
  for (let i = 0; i < curated.length; i++) {
    for (let j = i + 1; j < curated.length; j++) {
      scores[pairKey(curated[i].id, curated[j].id)] = pairScore(curated[i].id, curated[j].id);
    }
  }
  for (const p of imported) {
    seedDataset.policies
      .filter((q) => q.id !== p.id)
      .map((q) => ({ id: q.id, score: pairScore(p.id, q.id) }))
      .sort((x, y) => y.score - x.score)
      .slice(0, IMPORTED_NEIGHBOURS)
      .forEach(({ id, score }) => {
        scores[pairKey(p.id, id)] = score;
      });
  }

  const semanticFile = path.join(process.cwd(), "src/data/seed/semantic.ts");
  writeFileSync(
    semanticFile,
    `/** GENERATED by pnpm embed — do not edit. */\nexport const SEMANTIC_MODEL = ${JSON.stringify(MODEL)};\n\nexport const semanticScores: Record<string, number> = ${JSON.stringify(scores, null, 2)};\n`,
  );
  console.log(`wrote ${semanticFile} (${Object.keys(scores).length} policy pairs)`);
}

main();
