import type {
  Dataset,
  Policy,
  Similarity,
} from "@/lib/domain/schema";
import { Sector } from "@/lib/domain/schema";
import {
  POLICY_EXTRACTION_SYSTEM_PROMPT,
  EVIDENCE_EXTRACTION_SYSTEM_PROMPT,
} from "@/lib/ai/prompts";
import type { LLMProvider } from "@/lib/ai/provider";
import { structuredSimilarity } from "@/lib/similarity/structured";
import { cosine } from "@/lib/similarity/engine";
import { extractFromPdf, extractFromText, extractFromUrl } from "./extract-text";
import { chunkText } from "./chunk";
import {
  ExtractedEntities,
  ExtractedRelations,
  PolicyChunkExtraction,
  type ExtractedEntitiesT,
  type ExtractedRelationsT,
  type ExtractedPolicyT,
  type Provenance,
} from "./schemas";

export const STAGES = [
  "SOURCE",
  "TEXT EXTRACTION",
  "CHUNKING",
  "POLICY EXTRACTION",
  "ENTITY EXTRACTION",
  "RELATIONSHIP EXTRACTION",
  "EMBEDDINGS",
  "SIMILARITY",
  "HUMAN REVIEW",
  "PUBLISH",
] as const;
export type StageName = (typeof STAGES)[number];

export interface PipelineInput {
  kind: "URL" | "PDF" | "TEXT";
  url?: string;
  text?: string;
  pdf?: Uint8Array;
  label: string;
}

export interface ReviewDraft {
  /** first merged extracted policy, materialised as a Policy record */
  policy: Policy | null;
  /** field name → provenance for the drafted policy */
  provenance: Record<string, Provenance>;
  /** top similar seeded policies */
  similar: Similarity[];
  entities: ExtractedEntitiesT;
  relations: ExtractedRelationsT["relations"];
  chunkCount: number;
  textLength: number;
  /** number of extra policies extracted beyond the drafted one */
  extraPolicies: number;
  warnings: string[];
}

export interface PipelineResult {
  status: "NEEDS_PROVIDER" | "IN_REVIEW";
  stagesDone: StageName[];
  draft: ReviewDraft | null;
}

/** Policy embeddings generated by `pnpm embed` (absent until then). */
let policyEmbCache: Map<string, number[]> | null = null;
async function policyEmbeddings(): Promise<Map<string, number[]>> {
  if (policyEmbCache) return policyEmbCache;
  policyEmbCache = new Map();
  try {
    // server-side only — pipeline runs in API routes
    const fs = await import("node:fs");
    const path = await import("node:path");
    const file = path.join(process.cwd(), "src/data/seed/embeddings.json");
    if (fs.existsSync(file)) {
      const j = JSON.parse(fs.readFileSync(file, "utf8")) as {
        policies?: Record<string, number[]>;
      };
      policyEmbCache = new Map(Object.entries(j.policies ?? {}));
    }
  } catch {
    /* embeddings optional */
  }
  return policyEmbCache;
}

const norm = (s: string) =>
  s.toLowerCase().replace(/[^a-z0-9]+/g, " ").trim();

const slug = (s: string) =>
  norm(s).replace(/\s+/g, "_").slice(0, 40) || "untitled";

function sectorFrom(text: string | null): Policy["sector"] {
  const t = (text ?? "").toLowerCase();
  for (const s of Sector.options) {
    if (t === s.toLowerCase() || t === s.toLowerCase().replace(/_/g, " ")) return s;
  }
  if (t.includes("residential") || t.includes("home")) return "RESIDENTIAL_BUILDINGS";
  if (t.includes("commercial")) return "COMMERCIAL_BUILDINGS";
  if (t.includes("public")) return "PUBLIC_BUILDINGS";
  return "ALL_BUILDINGS";
}

function fuzzyId(
  name: string,
  items: { id: string; name: string }[],
): string | null {
  const n = norm(name);
  if (!n) return null;
  const exact = items.find((i) => norm(i.name) === n || i.id === n);
  if (exact) return exact.id;
  const contains = items.find((i) => norm(i.name).includes(n) || n.includes(norm(i.name)));
  return contains?.id ?? null;
}

function materialise(
  ep: ExtractedPolicyT,
  dataset: Dataset,
  label: string,
  takenIds: Set<string>,
): { policy: Policy; warnings: string[] } {
  const warnings: string[] = [];
  const name = ep.policy_name.value?.trim() || `Ingested policy (${label})`;

  // jurisdiction: fuzzy name match, else national jurisdiction for the country
  let jur = dataset.jurisdictions.find(
    (j) => ep.jurisdiction.value && norm(j.name) === norm(ep.jurisdiction.value),
  );
  if (!jur && ep.jurisdiction.value) {
    jur = dataset.jurisdictions.find((j) =>
      norm(j.name).includes(norm(ep.jurisdiction.value!)),
    );
  }
  const country = ep.country.value ?? jur?.country_code;
  if (!jur && country) {
    jur = dataset.jurisdictions.find(
      (j) => j.country_code === country && j.level !== "CITY",
    );
  }
  if (!jur) {
    warnings.push("Could not resolve a jurisdiction — using the first national one.");
    jur = dataset.jurisdictions.find((j) => j.level === "NATIONAL")!;
  }

  // mechanisms: match by kind to existing mechanism ids
  const mechIds = (ep.mechanisms.value ?? [])
    .map((kind) => dataset.mechanisms.find((m) => m.kind === kind)?.id)
    .filter((x): x is string => Boolean(x));

  const techIds = (ep.technologies.value ?? [])
    .map((t) => fuzzyId(t, dataset.technologies))
    .filter((x): x is string => Boolean(x));

  let base = `pol_ingest_${slug(name)}`;
  let id = base;
  for (let i = 2; takenIds.has(id); i++) id = `${base}_${i}`;
  takenIds.add(id);

  const policy: Policy = {
    id,
    name,
    jurisdiction_id: jur.id,
    country_code: jur.country_code,
    status: ep.status.value ?? "ANNOUNCED",
    introduced: ep.introduced_date.value ?? String(new Date().getFullYear()),
    ended: null,
    sector: sectorFrom(ep.sector.value),
    technology_ids: techIds,
    mechanism_ids: mechIds,
    target_groups: ep.target_groups.value ?? [],
    eligibility: ep.eligibility.value ?? "Not stated in source.",
    incentive: ep.incentives.value ?? "Not stated in source.",
    funding: ep.funding.value ?? "Not stated in source.",
    objectives: ep.policy_objectives.value ?? [],
    description: ep.description.value ?? "No description extracted.",
    limitations: [],
    sources: [
      {
        label: ep.source.value || label,
        url: null,
        publisher: "PACT ingestion",
      },
    ],
    // ingested records stay DEMO until a human verifies and curates them
    data_status: "DEMO",
    tags: ["ingested"],
  };
  return { policy, warnings };
}

/** Merge chunk extractions by normalised policy name (first wins). */
function mergeExtractions(
  all: { chunk: number; policies: ExtractedPolicyT[] }[],
  warnings: string[],
): ExtractedPolicyT[] {
  const byName = new Map<string, ExtractedPolicyT>();
  for (const { policies } of all) {
    for (const p of policies) {
      const key = norm(p.policy_name.value ?? "");
      if (!key) continue;
      if (!byName.has(key)) {
        byName.set(key, p);
      } else {
        warnings.push(`Duplicate extraction for "${p.policy_name.value}" merged.`);
      }
    }
  }
  return [...byName.values()];
}

function provenanceOf(ep: ExtractedPolicyT): Record<string, Provenance> {
  const out: Record<string, Provenance> = {};
  for (const [k, v] of Object.entries(ep)) {
    if (v && typeof v === "object" && "provenance" in v && v.provenance) {
      out[k] = v.provenance as Provenance;
    }
  }
  return out;
}

/**
 * Run the ingestion pipeline. Text extraction and chunking always run for
 * real; LLM stages require a configured provider — without one the job ends at
 * NEEDS_PROVIDER with a clear message and no fabricated extraction.
 */
export async function runPipeline(
  input: PipelineInput,
  dataset: Dataset,
  provider: LLMProvider,
  onStage?: (stage: StageName) => void,
): Promise<PipelineResult> {
  const done = (s: StageName) => onStage?.(s);
  const warnings: string[] = [];
  done("SOURCE");

  // TEXT EXTRACTION
  const text =
    input.kind === "URL"
      ? await extractFromUrl(input.url!)
      : input.kind === "PDF"
        ? await extractFromPdf(input.pdf!)
        : extractFromText(input.text ?? "");
  if (!text) throw new Error("no text extracted");
  done("TEXT EXTRACTION");

  // CHUNKING
  const chunks = chunkText(text);
  done("CHUNKING");

  if (!provider.isConfigured()) {
    warnings.push(
      "LLM provider not configured (OPENROUTER_API_KEY) — text was extracted and chunked, but policy extraction needs a provider.",
    );
    return {
      status: "NEEDS_PROVIDER",
      stagesDone: ["SOURCE", "TEXT EXTRACTION", "CHUNKING"],
      draft: {
        policy: null,
        provenance: {},
        similar: [],
        entities: { technologies: [], mechanisms: [], jurisdictions: [], metrics: [] },
        relations: [],
        chunkCount: chunks.length,
        textLength: text.length,
        extraPolicies: 0,
        warnings,
      },
    };
  }

  // POLICY EXTRACTION (per chunk; malformed output becomes a warning)
  const extracted: { chunk: number; policies: ExtractedPolicyT[] }[] = [];
  for (let i = 0; i < chunks.length; i++) {
    try {
      const { data } = await provider.chatJSON({
        system: POLICY_EXTRACTION_SYSTEM_PROMPT,
        user: `CHUNK ${i} of ${chunks.length}:\n\n${chunks[i]}`,
        schema: PolicyChunkExtraction,
        schemaName: "policy_extraction",
        maxTokens: 3000,
      });
      extracted.push({ chunk: i, policies: data.policies });
    } catch (err) {
      warnings.push(
        `Chunk ${i} policy extraction failed: ${err instanceof Error ? err.message : String(err)}`,
      );
    }
  }
  done("POLICY EXTRACTION");

  // ENTITY + RELATIONSHIP EXTRACTION (per chunk, tolerant)
  const entities: ExtractedEntitiesT = {
    technologies: [],
    mechanisms: [],
    jurisdictions: [],
    metrics: [],
  };
  const relations: ExtractedRelationsT["relations"] = [];
  for (let i = 0; i < chunks.length; i++) {
    try {
      const { data } = await provider.chatJSON({
        system: EVIDENCE_EXTRACTION_SYSTEM_PROMPT,
        user: `List the technologies, mechanisms, jurisdictions and metrics mentioned in this excerpt. CHUNK ${i}:\n\n${chunks[i]}`,
        schema: ExtractedEntities,
        schemaName: "entity_extraction",
        maxTokens: 1500,
      });
      for (const k of ["technologies", "mechanisms", "jurisdictions", "metrics"] as const)
        entities[k].push(...data[k]);
    } catch (err) {
      warnings.push(`Chunk ${i} entity extraction failed: ${err instanceof Error ? err.message : String(err)}`);
    }
    try {
      const { data } = await provider.chatJSON({
        system: EVIDENCE_EXTRACTION_SYSTEM_PROMPT,
        user: `List relationships between the policies and entities mentioned. CHUNK ${i}:\n\n${chunks[i]}`,
        schema: ExtractedRelations,
        schemaName: "relation_extraction",
        maxTokens: 1500,
      });
      relations.push(...data.relations);
    } catch (err) {
      warnings.push(`Chunk ${i} relation extraction failed: ${err instanceof Error ? err.message : String(err)}`);
    }
  }
  done("ENTITY EXTRACTION");
  done("RELATIONSHIP EXTRACTION");

  const merged = mergeExtractions(extracted, warnings);
  const taken = new Set(dataset.policies.map((p) => p.id));
  const drafted = merged.length ? materialise(merged[0], dataset, input.label, taken) : null;
  if (drafted) warnings.push(...drafted.warnings);
  if (merged.length > 1)
    warnings.push(`${merged.length - 1} additional extracted policies not drafted for review.`);

  // EMBEDDINGS (optional — for semantic similarity)
  let embedding: number[] | null = null;
  if (drafted) {
    try {
      const [vec] = await provider.embed([
        `${drafted.policy.name}\n${drafted.policy.description}\n${drafted.policy.incentive}`,
      ]);
      embedding = vec;
    } catch {
      warnings.push("Embedding failed — similarity is structural only.");
    }
  }
  done("EMBEDDINGS");

  // SIMILARITY vs seeded policies (structural + semantic when embeddings exist)
  const similar: Similarity[] = [];
  if (drafted) {
    const jurs = dataset.jurisdictions;
    const embMap = embedding ? await policyEmbeddings() : new Map<string, number[]>();
    similar.push(
      ...dataset.policies
        .map((p) => {
          const pe = embMap.get(p.id);
          const semantic =
            embedding && pe
              ? Math.max(0, Math.min(1, (cosine(embedding, pe) + 1) / 2))
              : undefined;
          return { p, bd: structuredSimilarity(drafted.policy, p, jurs, semantic) };
        })
        .filter((r) => r.bd.overall >= 0.5)
        .map((r) => {
          return {
            id: `sim_${[drafted.policy.id, r.p.id].sort().join("_")}`,
            policy_a: drafted.policy.id,
            policy_b: r.p.id,
            breakdown: r.bd,
          } satisfies Similarity;
        })
        .sort((a, b) => b.breakdown.overall - a.breakdown.overall)
        .slice(0, 5),
    );
  }
  done("SIMILARITY");
  done("HUMAN REVIEW");

  return {
    status: "IN_REVIEW",
    stagesDone: [
      "SOURCE",
      "TEXT EXTRACTION",
      "CHUNKING",
      "POLICY EXTRACTION",
      "ENTITY EXTRACTION",
      "RELATIONSHIP EXTRACTION",
      "EMBEDDINGS",
      "SIMILARITY",
      "HUMAN REVIEW",
    ],
    draft: {
      policy: drafted?.policy ?? null,
      provenance: drafted ? provenanceOf(merged[0]) : {},
      similar,
      entities,
      relations,
      chunkCount: chunks.length,
      textLength: text.length,
      extraPolicies: Math.max(0, merged.length - 1),
      warnings,
    },
  };
}
